- hosts: myservers
  remote_user: sysadmin
  sudo: true

  tasks:
    - name: Install redis
      yum: name=redis

    - name: Create redis group
      group: name=redis

    - name: Create redis user
      user: name=redis group=redis

    - name: Create log folder
      file: path=/var/log/redis state=directory
            owner=redis group=redis mode=0700 

    - name: Start redis
      service: name=redis state=started
