- hosts: myservers
  remote_user: sysadmin
  gather_facts: no

  tasks:
    - name: Install packages
      yum: name={{ item }} state=latest
      with_items:
        - httpd
        - httpd-devel
        - mod_ssl
        - openssh
	- libselinux-python
